---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: default
  annotations:
  labels:
    app: jaeger
spec:
  type: NodePort
  selector:
    app: jaeger
  ports:
  - name: udp
    port: 5775
    protocol: UDP
  - name: api
    port: 16686
    protocol: TCP
    nodePort: 30000
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jaeger
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: system:jaeger
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:jaeger
subjects:
- kind: ServiceAccount
  name: jaeger
  namespace: default
---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: jaeger
  namespace: default
spec:
  selector:
    matchLabels:
      app: jaeger
  serviceName: jaeger
  replicas: 1
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      serviceAccount: jaeger
      terminationGracePeriodSeconds: 10
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:latest
        ports:
        - containerPort: 5775
          name: udp
        - containerPort: 16686
          name: api
        livenessProbe:
          httpGet:
            path: /metrics
            port: api
          initialDelaySeconds: 3
          periodSeconds: 3
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: audit-trace
  namespace: default
  labels:
    app: audit-trace
spec:
  selector:
    matchLabels:
      app: audit-trace
  template:
    metadata:
      labels:
        app: audit-trace
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: audit-trace
        imagePullPolicy: Never
        image: quay.io/julienbalestra/audit-trace:master
        command:
        - /usr/local/bin/audit-trace
        - --audit-log-path=/opt/sandbox/logs/audit.log
        - --trace-agent-endpoint=jaeger.default.svc.cluster.local:5775
        - --agent=jaeger
        - -v=2
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: audit-log
          mountPath: /opt/sandbox/logs
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: audit-log
        hostPath:
          path: /opt/sandbox/logs
---
